#!/usr/bin/env bash
# =============================================================================
# build_school_payload.sh — assemble the school-server deployment zip
# =============================================================================
# Run on jhm-spark, from the repo root, AFTER generate_pdfs.js and
# generate_teacher_index.js. Produces:
#
#     dist/ares-cbe-payload-<YYYYMMDD>.zip
#
# containing:
#     install.sh                  provisioning script (deploy/install.sh)
#     ares-mdns-alias.sh          mDNS publisher
#     ares-mdns-alias.service     systemd unit
#     generate_teacher_index.js   DEPLOYED variant, PDF_ROOT = __dirname
#     PDF/                        the whole v2/PDF tree, 255 docs + index.html
#     index.htmlf                 module landing page, if one is supplied
#     MANIFEST.txt                what went in, and the verified link host
#
# Why a builder rather than a hand-assembled zip: the payload was previously
# built by hand, never committed, and the docs' claim that it existed could not
# be checked. Same failure as scripts/sync_to_drive.bat. This makes it
# reproducible and greppable.
#
# The deployed generate_teacher_index.js is DERIVED here from the repo copy by
# rewriting PDF_ROOT, rather than being a second hand-maintained file. The two
# copies genuinely need different PDF_ROOT values (repo walks up to
# data/outputs/v2/PDF; the deployed one sits inside PDF/), and STATUS.md notes
# there was no automated sync between them. Deriving it removes that drift.
# =============================================================================
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

PDF_SRC="data/outputs/v2/PDF"
DEPLOY_DIR="deploy"
OUT_DIR="dist"
STAMP="$(date +%Y%m%d)"
STAGE="$(mktemp -d)"
NAME="ares-cbe-payload-$STAMP"
trap 'rm -rf "$STAGE"' EXIT

fail() { echo "ERROR: $*" >&2; exit 1; }

echo "=== Building $NAME ==="

# --- Pre-flight --------------------------------------------------------------
[[ -d "$PDF_SRC" ]] || fail "$PDF_SRC not found — run generators/generate_pdfs.js first"
PDF_COUNT="$(find "$PDF_SRC" -name '*.pdf' | wc -l)"
(( PDF_COUNT > 0 )) || fail "$PDF_SRC contains no PDFs"
[[ -f "$PDF_SRC/index.html" ]] \
    || fail "$PDF_SRC/index.html missing — run generators/generate_teacher_index.js"

for f in install.sh ares-mdns-alias.sh ares-mdns-alias.service; do
    [[ -f "$DEPLOY_DIR/$f" ]] || fail "$DEPLOY_DIR/$f missing"
done

# --- Hard gate: resource links must be ares.local ----------------------------
# This is the check whose absence let a corpus-wide regression ship. A payload
# with ares.edu links installs fine and fails silently on every school network,
# so refuse to build one rather than warn about it.
# `|| true` matters: grep exits 1 when it finds nothing, and with `pipefail` that
# would abort the script on the success path.
EDU_HITS="$({ grep -rlI 'ares\.edu' "$PDF_SRC" 2>/dev/null || true; } | wc -l)"
if (( EDU_HITS > 0 )); then
    echo "  $EDU_HITS file(s) in $PDF_SRC still reference ares.edu:" >&2
    { grep -rlI 'ares\.edu' "$PDF_SRC" 2>/dev/null || true; } | head -5 >&2
    fail "refusing to build. Regenerate the corpus (ARES_HOST defaults to
       ares.local in src/ares_recommender.py) and re-run generate_pdfs.js."
fi
echo "  link host check: 0 ares.edu references — OK"

# --- Stage -------------------------------------------------------------------
mkdir -p "$STAGE/$NAME"
install -m 0755 "$DEPLOY_DIR/install.sh"             "$STAGE/$NAME/install.sh"
install -m 0755 "$DEPLOY_DIR/ares-mdns-alias.sh"     "$STAGE/$NAME/ares-mdns-alias.sh"
install -m 0644 "$DEPLOY_DIR/ares-mdns-alias.service" "$STAGE/$NAME/ares-mdns-alias.service"

# Deployed teacher-index variant: PDF_ROOT = __dirname (it lives inside PDF/).
sed -E "s|^const PDF_ROOT = .*|const PDF_ROOT = __dirname;  // deployed copy: this file sits inside PDF/|" \
    generators/generate_teacher_index.js > "$STAGE/$NAME/generate_teacher_index.js"
grep -q 'const PDF_ROOT = __dirname;' "$STAGE/$NAME/generate_teacher_index.js" \
    || fail "PDF_ROOT rewrite failed — has generate_teacher_index.js line 7 changed shape?"
echo "  derived deployed generate_teacher_index.js (PDF_ROOT = __dirname)"

# index.htmlf is optional: it is not generated by this repo. Supply it via
# deploy/index.htmlf and it gets bundled; otherwise the installer leaves the
# server's existing landing page untouched.
if [[ -f "$DEPLOY_DIR/index.htmlf" ]]; then
    install -m 0644 "$DEPLOY_DIR/index.htmlf" "$STAGE/$NAME/index.htmlf"
    echo "  included index.htmlf"
else
    echo "  no deploy/index.htmlf — landing page will be left alone on the server"
fi

cp -a "$PDF_SRC" "$STAGE/$NAME/PDF"
echo "  staged $PDF_COUNT PDFs + index.html"

# --- Manifest ----------------------------------------------------------------
{
    echo "ARES CBE lesson-plan payload"
    echo "built:        $(date -Iseconds)"
    echo "host:         $(hostname)"
    echo "git commit:   $(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    echo "git branch:   $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
    echo "pdf count:    $PDF_COUNT"
    echo "subjects:     $(find "$PDF_SRC" -mindepth 1 -maxdepth 1 -type d | wc -l)"
    echo "link host:    ares.local (verified 0 ares.edu references at build time)"
    echo
    echo "Install with:  sudo ./install.sh --dry-run   then   sudo ./install.sh"
} > "$STAGE/$NAME/MANIFEST.txt"

# --- Zip ---------------------------------------------------------------------
command -v zip >/dev/null 2>&1 || fail "zip not installed (sudo apt install zip)"
mkdir -p "$OUT_DIR"
rm -f "$OUT_DIR/$NAME.zip"
( cd "$STAGE" && zip -rq "$NAME.zip" "$NAME" )
mv "$STAGE/$NAME.zip" "$OUT_DIR/$NAME.zip"

SIZE="$(du -h "$OUT_DIR/$NAME.zip" | cut -f1)"
echo
echo "=== Done ==="
echo "  $OUT_DIR/$NAME.zip  ($SIZE)"
echo
echo "  Next: copy to one ARES server, unzip, then:"
echo "    cd $NAME && sudo ./install.sh --dry-run"
echo "    sudo ./install.sh"
echo "  Test ares.local from a DIFFERENT device on the same network."
