#!/usr/bin/env python3
"""
rebuild_consistency.py — bring the Summary Table and Final Explanation of
existing sub-strands back in line with their lessons.
==========================================================================
Why this exists (2026-10-03): the partner's validator found that a sub-strand's
Summary Table described different lessons from the lesson sequence, and its
Final Explanation used a different dataset (and contradicted itself). Cause:
all three documents were generated by separate calls; the Final Explanation
(batch mode) never saw the lessons, and the Summary Table was free to retitle
them. 73 of 85 Grade 10 sub-strands had at least one retitled lesson.

  --summary-tables      Rewrite SUMMARY_TABLE in every generators/data/*_data.js
                        from that module's own LESSONS (title + summaryTablePrompt).
                        No API call, free, idempotent.
  --final-explanations  Regenerate FINAL_EXPLANATION from the lesson content, have a
                        second call review it for contradictions, retry with the
                        reviewer's findings (<= 3 rounds). Written ONLY if the
                        review comes back clean; otherwise the old text is left
                        in place and the candidate + issues go to
                        logs/final_explanation_issues/. Costs API money.

  --apply-held          write the saved best attempt (logs/final_explanation_issues/
                        <module>_candidate.json) of every module an earlier run held back,
                        flagged needs_review. No API call.
  --clear MODULE        mark a flagged module as human-reviewed and acceptable
                        (needs --by "Name" and --note "..."); the validator then passes it.
  --only a,b            module names without _data.js (e.g. coremath_2_9,bio_1_1)
  --dry-run             show what would run (and, for FE, the cost estimate); write nothing
  --workers N           parallel FE calls (default 4)

After either step, re-render: node generators/generate.js --all   (or per module),
then node generators/generate_pdfs.js && node generators/generate_teacher_index.js,
and run scripts/validate_consistency.py.
"""
import argparse
import json
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "generators" / "data"
sys.path.insert(0, str(ROOT / "src"))


def load_module(path: Path) -> dict:
    out = subprocess.run(
        ["node", "-e", "process.stdout.write(JSON.stringify(require(process.argv[1])))", str(path)],
        capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def replace_block(src: str, const: str, value) -> str:
    """Replace `const <const> = ...;` (object literal or null) with `value`."""
    pat = re.compile(r"const " + const + r" = (?:null;|\{.*?\n\};)\n", re.S)
    if not pat.search(src):
        raise ValueError(f"const {const} block not found")
    body = "null" if value is None else json.dumps(value, indent=2, ensure_ascii=False)
    return pat.sub(lambda _m: f"const {const} = {body};\n", src, count=1)


def modules(only: list[str] | None) -> list[Path]:
    files = sorted(DATA.glob("*_data.js"))
    if only:
        wanted = {o.removesuffix("_data") for o in only}
        files = [f for f in files if f.name.removesuffix("_data.js") in wanted]
        missing = wanted - {f.name.removesuffix("_data.js") for f in files}
        if missing:
            sys.exit(f"unknown module(s): {sorted(missing)}")
    return files


def do_summary_tables(files: list[Path], dry: bool) -> None:
    from generate_substrand import derive_summary_table
    changed = 0
    for f in files:
        m = load_module(f)
        meta, unit, lessons = m["META"], m["UNIT"], m["LESSONS"]
        old = m.get("SUMMARY_TABLE") or {}
        new = derive_summary_table(unit, lessons, meta["substrand_id"], meta["substrand_name"])
        if old == new:
            continue
        changed += 1
        old_titles = [l.get("title") for l in (old.get("lessons") or [])]
        retitled = sum(1 for a, b in zip(old_titles, [l["title"] for l in new["lessons"]]) if a != b)
        print(f"  {f.name}: rewritten ({retitled} retitled)")
        if not dry:
            f.write_text(replace_block(f.read_text(), "SUMMARY_TABLE", new))
    print(f"Summary tables: {changed} of {len(files)} modules {'would change' if dry else 'rewritten'}.")


def do_final_explanations(files: list[Path], dry: bool, workers: int, max_spend: float = 35.0) -> int:
    import generate_substrand as g

    class A:  # args-like namespace the generator functions expect
        pass

    jobs = []
    for f in files:
        m = load_module(f)
        meta = m["META"]
        a = A()
        a.grade, a.subject = int(meta["grade"]), meta["subject"].lower()
        a.substrand, a.substrand_name = meta["substrand_id"], meta["substrand_name"]
        a.lessons, a.output = len(m["LESSONS"]), f.name.removesuffix("_data.js")
        jobs.append((f, m, a))
    # Rough cost: per module ~12k in + ~7k out for generation, ~14k in + ~1.5k out
    # per review round, ~1.4 rounds expected (measure the first run, then trust it).
    est = len(jobs) * (1.4 * (12e3 * 2 + 7e3 * 10) / 1e6 + 1.4 * (14e3 * 2 + 1.5e3 * 10) / 1e6)
    print(f"Final Explanations: {len(jobs)} module(s), estimated ~${est:.2f} (live, sonnet-5-5).")
    if dry:
        for f, _, a in jobs:
            print(f"  would regenerate: {a.output}")
        return 0

    def work(job):
        f, m, a = job
        if g._estimate_cost() > max_spend:
            return job, 'SKIPPED'
        t = g.find_v2_templates(a.grade, a.subject, a.substrand)
        fe_t = g.extract_template_docx(str(t["fe"])) if t.get("fe") else None
        lt = g.extract_template_docx(str(t["lesson"])) if t.get("lesson") else {}
        fe = g.generate_final_explanation("", m["UNIT"], m["LESSONS"], a, fe_template=fe_t,
                                          lesson_template=lt, log_name=a.output)
        return job, fe

    failed = 0
    issues_dir = ROOT / "logs" / "final_explanation_issues"
    with ThreadPoolExecutor(max_workers=workers) as ex:
        for fut in as_completed([ex.submit(work, j) for j in jobs]):
            (f, m, a), fe = fut.result()
            if fe == 'SKIPPED':
                failed += 1
                print(f"  SKIP   {a.output}: spend cap reached")
                continue
            log = issues_dir / f"{a.output}.json"
            if fe is not None:
                f.write_text(replace_block(f.read_text(), "FINAL_EXPLANATION", fe))
                if log.exists():
                    failed += 1
                    print(f"  REVIEW {a.output}: best attempt written, flagged needs_review ({log.relative_to(ROOT)})")
                else:
                    print(f"  OK     {a.output}")
            else:
                failed += 1
                print(f"  FAILED {a.output}: no Final Explanation produced; old text kept")
    print(f"Final Explanations: {len(jobs) - failed} clean, {failed} need review or failed.")
    try:
        print(f"Estimated spend this run: ${g._estimate_cost():.2f}")
    except Exception:
        pass
    return 1 if failed else 0


def do_apply_held() -> int:
    d = ROOT / "logs" / "final_explanation_issues"
    n = 0
    for cand in sorted(d.glob("*_candidate.json")):
        name = cand.name.removesuffix("_candidate.json")
        mod = DATA / f"{name}_data.js"
        log = d / f"{name}.json"
        if not mod.exists() or not log.exists():
            continue
        mod.write_text(replace_block(mod.read_text(), "FINAL_EXPLANATION", json.loads(cand.read_text())))
        meta = json.loads(log.read_text())
        meta["status"] = "needs_review"
        log.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
        cand.unlink()
        n += 1
        print(f"  applied best attempt: {name} (needs_review)")
    print(f"{n} held module(s) applied.")
    return 0


def do_clear(name: str, by: str | None, note: str) -> int:
    import datetime
    log = ROOT / "logs" / "final_explanation_issues" / f"{name}.json"
    if not log.exists():
        sys.exit(f"no review flag for {name}")
    if not by:
        sys.exit("--clear needs --by \"Name\" (who reviewed it)")
    meta = json.loads(log.read_text())
    meta.update(status="cleared", cleared_by=by, cleared_note=note,
                cleared_on=datetime.date.today().isoformat())
    log.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
    print(f"{name}: cleared by {by}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--summary-tables", action="store_true")
    ap.add_argument("--final-explanations", action="store_true")
    ap.add_argument("--apply-held", action="store_true")
    ap.add_argument("--clear")
    ap.add_argument("--by")
    ap.add_argument("--note", default="")
    ap.add_argument("--only")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--max-spend", type=float, default=35.0, help="stop starting new modules above this estimated $")
    a = ap.parse_args()
    if a.clear:
        return do_clear(a.clear, a.by, a.note)
    if a.apply_held:
        return do_apply_held()
    if not (a.summary_tables or a.final_explanations):
        ap.error("choose --summary-tables and/or --final-explanations")
    files = modules(a.only.split(",") if a.only else None)
    rc = 0
    if a.summary_tables:
        do_summary_tables(files, a.dry_run)
    if a.final_explanations:
        rc = do_final_explanations(files, a.dry_run, a.workers, a.max_spend)
    return rc


if __name__ == "__main__":
    sys.exit(main())
